trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker build -f Dockerfile  -t $(image) .
    docker login -u $(dockerId) -p $(pwd) $(registry)
    docker tag $(image) $(registry)/$(namespace)/$(image)
    docker push $(registry)/$(namespace)/$(image)

  displayName: 推送腾讯云镜像