trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  registryPath: https://ccr.ccs.tencentyun.com/
 

steps:
- script: |
    docker build -f Dockerfile  -t $(image) .
    docker login -u $(dockerId) -p $(pwd) $(registryPath)
    docker tag $(image) $(registry)/$(namespace)/$(image)
    docker push $(registry)/$(namespace)/$(image)

  displayName: 推送腾讯云镜像