trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: '$(dockerId)/$(image)'

steps:
- script: |

    docker build -f Dockerfile -t $(image):latest .
    docker login -u $(dockerId) -p $(pwd)
    docker tag $(image):latest $(imageName):latest
    docker push $(imageName):latest



    # docker build -f Dockerfile  -t $(image) .
    # docker login -u $(dockerId) -p $(pwd) $(registry)
    # docker tag $(image) $(registry)/$(namespace)/$(image)
    # docker push $(registry)/$(namespace)/$(image)

  displayName: 推送Docker镜像