trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


 

steps:
- script: |
    docker build -f Dockerfile  -t pomelobutterblazor .
    sudo docker login --username=$(dockerId) $(registry)
    sudo docker tag pomelobutter $(registry)/$(namespace)/$(image):dev
    sudo docker push $(registry)/$(namespace)/$(image):dev

  displayName: push to DockerHub