trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:

  imageName: '$(dockerId)/pomelobutterblazor'


steps:
- script: |
    docker build -f Dockerfile -t $(imageName) .
    docker login -u $(dockerId) -p $(pswd) $(registry)
    docker push $(imageName)

  displayName: push to DockerHub