trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


 

steps:
- script: |
    sudo docker login --username=$(dockerId) $(registry)
    sudo docker tag [ImageId] $(registry)/$(namespace)/$(image):[tag]
    sudo docker push $(registry)/$(namespace)/$(image):[tag]

  displayName: push to DockerHub