trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


 

steps:
- script: |
    docker build -f Dockerfile  -t $(image) .
    sudo docker login --username=$(dockerId) $(registry)
    sudo docker tag $(image) $(registry)/$(namespace)/$(image)
    sudo docker push $(registry)/$(namespace)/$(image)

  displayName: 推送腾讯云镜像