pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: '$(dockerId)/pomelobutterblazor'

steps:

- script: |
    docker build -f Dockerfile -t $(imageName) .
    docker login -u $(dockerId) -p $(pwd)
    docker push $(imageName)